const lang = window.navigator.language === 'zh-CN' ? 'zh' : 'en';

export default {
  en: {
    leftBgColor: 'Left Color',
    rightBgColor: 'Right Color',
    copy: 'Copy ',
    createLink: 'Create Link ',
    download: 'Download',
    errorMsg: 'Error, Try again later!',
    fileSaver: 'File Saver',
    gradient: 'Gradient',
    icon: 'Select Icon',
    iconColor: 'Icon Color',
    leftText: 'Left Text',
    link: 'Link',
    linkConvertor: 'Link Convertor',
    markdown: 'Markdown',
    preview: 'Preview',
    result: 'Result',
    rightText: 'Right Text',
    roundedAngle: 'Rounded',
    select: 'Select',
    success: 'Success',
    textShadow: 'Text Shadow',
    title: 'Customize NPM Badge',
  },
  zh: {
    leftBgColor: '左背景色',
    rightBgColor: '右背景色',
    copy: '复制',
    createLink: '生成链接',
    download: '下载',
    errorMsg: '请求出错，稍后重试！',
    fileSaver: '文件存储',
    gradient: '渐变底色',
    icon: '选择图标',
    iconColor: '图标颜色',
    leftText: '左边文字',
    link: '链接',
    linkConvertor: '链接转换',
    markdown: 'Markdown',
    preview: '预览',
    result: '结果',
    rightText: '右边文字',
    roundedAngle: '使用圆角',
    select: '请选择',
    success: '成功',
    textShadow: '文字阴影',
    title: '在生成NPM徽标链接',
  },
}[lang];
